Repository AY2425S2-CS2103T-W13-4/tp, pull requests merged in 2025-04, with the labels that each got.

#98 Fix `undo`/`redo` command and add proper success message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/AddressBookStateNode.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/modifications/AddMod.java
  src/main/java/seedu/address/model/modifications/DeleteMod.java
  src/main/java/seedu/address/model/modifications/EditMod.java
  src/main/java/seedu/address/model/modifications/Modification.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Epic, priority.High, due: Wednesday

#120 Fix bugs in filter and update UG description of filter
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: severity.High, due: Thursday, alpha-bug

#105 Rework import command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/FileBasedCommandTest/addressbook.json
  src/test/data/FileBasedCommandTest/duplicate_person_address_book.json
  src/test/data/FileBasedCommandTest/empty.json
  src/test/data/FileBasedCommandTest/expected_json_append_dupe_email.json
  src/test/data/FileBasedCommandTest/expected_json_append_dupe_phone.json
  src/test/data/FileBasedCommandTest/expected_json_append_no_dupe.json
  src/test/data/FileBasedCommandTest/expected_json_overwrite_dupe.json
  src/test/data/FileBasedCommandTest/invalid_contacts.json
  src/test/data/FileBasedCommandTest/not_json.txt
  src/test/data/FileBasedCommandTest/preferences.json
  src/test/data/FileBasedCommandTest/valid_contacts.json
  src/test/data/FileBasedCommandTest/valid_json_dupe_email.json
  src/test/data/FileBasedCommandTest/valid_json_dupe_phone.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonsAddressBook2.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/FileUtil.java
Labels: type.Enhancement, priority.Medium, severity.Medium, due: Wednesday

#126 Reformat export success message
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Bug, severity.Low, alpha-bug

#114 Improve `undo`/`redo`
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/AddressBookStateManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/modifications/AddMod.java
  src/main/java/seedu/address/model/modifications/ClearMod.java
  src/main/java/seedu/address/model/modifications/DeleteMod.java
  src/main/java/seedu/address/model/modifications/EditMod.java
  src/main/java/seedu/address/model/modifications/Modification.java
  src/main/java/seedu/address/model/modifications/ModificationWithTarget.java
  src/main/java/seedu/address/model/modifications/NoteMod.java
  src/test/data/FileBasedCommandTest/preferences.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/RedoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
Labels: type.Enhancement, due: Thursday

#127 Fix incorrect duplication of undo in UG
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow, alpha-bug

#128 Rename title of DG to CraftConnect DG
  docs/DeveloperGuide.md
Labels: type.Bug, severity.VeryLow, alpha-bug

#129 Improve UG ahead of PE-D
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/resources/images/command_summary.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.VeryLow, due: Friday, alpha-bug

#118 Fix delete message and update import's UG, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, due: Thursday, alpha-bug

#184 Fix PE-D bugs for filter
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/data/FileBasedCommandTest/preferences.json
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: type.Bug, priority.High, severity.Low

#182 Hardcode limit to undo/redo and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/test/java/seedu/address/logic/parser/RedoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
Labels: type.Bug, priority.High, due: Tuesday

#191 Update UG for filter
  docs/UserGuide.md
Labels: due: Tuesday

#193 Add puml diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelObjectDiagram.puml
Labels: type.Task

#199 Update help message to include exit
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/resources/images/command_summary.png
Labels: type.Bug, due: Tuesday
